import type { Product } from './types';

export const products: Product[] = [
  {
    id: 1,
    name: "Women's Floral Print Kurta",
    description: "Elegant and comfortable floral print kurta, perfect for casual outings. Made with breathable cotton fabric.",
    price: 799,
    imageUrls: [
      "https://picsum.photos/seed/kurta1/600/800",
      "https://picsum.photos/seed/kurta2/600/800",
      "https://picsum.photos/seed/kurta3/600/800",
    ],
  },
  {
    id: 2,
    name: "Men's Solid Color Shirt",
    description: "A classic solid color shirt for men. Versatile for both formal and casual wear. Premium linen blend.",
    price: 999,
    imageUrls: [
      "https://picsum.photos/seed/shirt1/600/800",
      "https://picsum.photos/seed/shirt2/600/800",
      "https://picsum.photos/seed/shirt3/600/800",
    ],
  },
  {
    id: 3,
    name: "Designer Silk Saree",
    description: "Exquisite designer silk saree with intricate patterns. Comes with a matching blouse piece. Ideal for weddings.",
    price: 2499,
    imageUrls: [
      "https://picsum.photos/seed/saree1/600/800",
      "https://picsum.photos/seed/saree2/600/800",
      "https://picsum.photos/seed/saree3/600/800",
    ],
  },
  {
    id: 4,
    name: "Kids' Graphic T-Shirt",
    description: "Fun and vibrant graphic t-shirt for kids. Made from 100% soft cotton to ensure all-day comfort.",
    price: 499,
    imageUrls: [
      "https://picsum.photos/seed/kidstee1/600/800",
      "https://picsum.photos/seed/kidstee2/600/800",
    ],
  },
  {
    id: 5,
    name: "Stylish Leather Handbag",
    description: "A stylish and spacious leather handbag for women. Features multiple compartments and a durable strap.",
    price: 1899,
    imageUrls: [
      "https://picsum.photos/seed/handbag1/600/800",
      "https://picsum.photos/seed/handbag2/600/800",
      "https://picsum.photos/seed/handbag3/600/800",
    ],
  },
  {
    id: 6,
    name: "Running Sports Shoes",
    description: "Lightweight and comfortable sports shoes, designed for running and gym workouts. Excellent grip and cushioning.",
    price: 2199,
    imageUrls: [
      "https://picsum.photos/seed/shoes1/600/800",
      "https://picsum.photos/seed/shoes2/600/800",
    ],
  },
  {
    id: 7,
    name: "Analog Wrist Watch",
    description: "A timeless analog wrist watch with a stainless steel strap. Water-resistant and perfect for daily use.",
    price: 1599,
    imageUrls: [
      "https://picsum.photos/seed/watch1/600/800",
      "https://picsum.photos/seed/watch2/600/800",
      "https://picsum.photos/seed/watch3/600/800",
    ],
  },
  {
    id: 8,
    name: "Bluetooth Earbuds",
    description: "True wireless bluetooth earbuds with noise cancellation and long battery life. Crystal clear sound quality.",
    price: 2999,
    imageUrls: [
      "https://picsum.photos/seed/earbuds1/600/800",
      "https://picsum.photos/seed/earbuds2/600/800",
    ],
  },
  {
    id: 9,
    name: "Modern Home Decor Vase",
    description: "A chic and modern ceramic vase to elevate your home decor. Perfect for fresh or artificial flowers.",
    price: 899,
    imageUrls: [
      "https://picsum.photos/seed/vase1/600/800",
      "https://picsum.photos/seed/vase2/600/800",
    ],
  },
  {
    id: 10,
    name: "Organic Cotton Bedsheet",
    description: "Soft and luxurious organic cotton bedsheet set. Includes one flat sheet and two pillow covers.",
    price: 1399,
    imageUrls: [
      "https://picsum.photos/seed/bedsheet1/600/800",
      "https://picsum.photos/seed/bedsheet2/600/800",
      "https://picsum.photos/seed/bedsheet3/600/800",
    ],
  },
];

export const indianStates: string[] = [
  "Andaman and Nicobar Islands",
  "Andhra Pradesh",
  "Arunachal Pradesh",
  "Assam",
  "Bihar",
  "Chandigarh",
  "Chhattisgarh",
  "Dadra and Nagar Haveli and Daman and Diu",
  "Delhi",
  "Goa",
  "Gujarat",
  "Haryana",
  "Himachal Pradesh",
  "Jammu and Kashmir",
  "Jharkhand",
  "Karnataka",
  "Kerala",
  "Ladakh",
  "Lakshadweep",
  "Madhya Pradesh",
  "Maharashtra",
  "Manipur",
  "Meghalaya",
  "Mizoram",
  "Nagaland",
  "Odisha",
  "Puducherry",
  "Punjab",
  "Rajasthan",
  "Sikkim",
  "Tamil Nadu",
  "Telangana",
  "Tripura",
  "Uttar Pradesh",
  "Uttarakhand",
  "West Bengal",
];